version: "3"
services:
  api_yuki:
    container_name: api_yuki
    depends_on:
      database_yuki:
        condition: service_healthy
    build: .
    volumes:
      # - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 49500:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  database_yuki:
    container_name: database_yuki
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 49555:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    devices:
      - "/dev/urandom:/dev/random"
volumes:
  mysql_data:
