version: "3"
services:
  api:
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 49500:8000
    networks:
      - teamc_network

  teamc_nginx:
    container_name: teamc_nginx
    image: nginx
    ports:
      # ポートマッピング： "ホストOSのポート:コンテナ(Nginx)のポート"
      - "49510:49510"
    volumes:
      - /home/teamC/DevSecOpsThon_server:/workspace
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - teamc-network

  db:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 49555:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 3s
      timeout: 10s
      retries: 10
    devices:
      - "/dev/urandom:/dev/random"
volumes:
  mysql_data:
networks:
  teamc_network:
    external: true
